version: "3"
services:
    stock:
        image: pythonstock/pythonstock:latest
        container_name: stock
        ports:
            - "8888:8888"
            - "9999:9999"
        volumes:
            - "./data/notebooks:/data/notebooks"
            - "./data/logs:/data/logs"
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PWD: mysqldb
            MYSQL_DB: stock_data
            LANG: en_US.UTF-8
            LC_ALL: en_US.UTF-8
        links:
            - mysqldb:mysqldb
        restart: always
    mysqldb:
        image: mysql:5.7
        container_name: mysqldb
        ports:
            - "3306:3306"
        volumes:
            - "./data/mariadb/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mysqldb
            MYSQL_DATABASE: stock_data
        restart: always
        
