version: "3"
services:
    stock:
        image: pythonstock/pythonstock:latest
        container_name: stock
        ports:
            - "8888:8888"
            - "9999:9999"
        volumes:
            - "./data/notebooks:/data/notebooks"
            - "./data/logs:/data/logs"
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: root
            MYSQL_PWD: mariadb
            MYSQL_DB: stock_data
            LANG: en_US.UTF-8
            LC_ALL: en_US.UTF-8
        links:
            - mariadb:mariadb
        restart: always
    mariadb:
        image: mariadb:10.5.6
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - "./data/mariadb/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
        restart: always
        
